root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ."
bin = "./tmp/server"
include_ext = ["go"]
exclude_dir = ["tmp", "infra", "bin", ".git", ".idea"]
delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
