ignore:
  - "main.go"
  - "core/db.go"
  - "book/repo.go"
  - "genre/repo.go"
  - "text/repo.go"
  - "relations/repo.go"
  - "translation/repo.go"
  - "search/repo.go"
  - "book/routes.go"
  - "genre/routes.go"
  - "text/routes.go"
  - "relations/routes.go"
  - "search/routes.go"
  - "translation/routes.go"
