services:
  go-api:
    build: .
    ports:
      - 8084:3000
    volumes:
      - .:/go/src/github.com/rkeplin/bible-go-api
    environment:
      - ES_URL=${ES_URL:-http://bible-es:9200}
      - DB_NAME=${BIBLE_DB_NAME:-bible}
      - DB_HOST=bible-db
      - DB_USER=${BIBLE_DB_USER:-bible}
      - DB_PASS=${BIBLE_DB_PASS:-changeme}
    depends_on:
      - bible-db
      - bible-es
    networks:
      - net1

  bible-db:
    image: rkeplin/bible-mariadb:v2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${BIBLE_DB_ROOT_PASS:-changeme}
      - MYSQL_USER=${BIBLE_DB_USER:-bible}
      - MYSQL_PASSWORD=${BIBLE_DB_PASS:-changeme}
      - MYSQL_DATABASE=${BIBLE_DB_NAME:-bible}
    volumes:
      - bible-db:/var/lib/mysql
    networks:
      - net1

  bible-es:
    image: rkeplin/bible-es:v3-nlt2015
    restart: always
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - net1

volumes:
  bible-db:

networks:
  net1:
